# Generated by Django 4.2.24 on 2025-09-29 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_number', models.CharField(max_length=30, unique=True)),
                ('planned_start', models.DateTimeField()),
                ('planned_end', models.DateTimeField(blank=True, null=True)),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('legal_entity', models.CharField(choices=[('llc', 'ООО (с НДС)'), ('sole', 'ИП (без НДС)')], default='llc', max_length=10)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RouteCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=1)),
                ('is_collected_by_collector', models.BooleanField(default=False)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.order')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.route')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='route',
            name='cargoes',
            field=models.ManyToManyField(through='logistics.RouteCargo', to='warehouse.order'),
        ),
        migrations.AddField(
            model_name='route',
            name='driver',
            field=models.ForeignKey(limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='route',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='vehicles.vehicle'),
        ),
    ]
