# Generated by Django 4.2.24 on 2025-10-02 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='planned_start',
            new_name='date_start',
        ),
    ]
