# Generated by Django 4.2.24 on 2025-10-05 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_rename_planned_start_route_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='route',
            name='planned_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
