# Generated by Django 4.2.24 on 2025-10-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_alter_route_date_start_alter_route_planned_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='date_start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='route',
            name='planned_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
