# Generated by Django 4.2.24 on 2025-09-29 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistics', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('comment', models.TextField(blank=True)),
                ('paid_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_records', to='logistics.route')),
            ],
        ),
        migrations.CreateModel(
            name='FuelTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liters', models.DecimalField(decimal_places=2, max_digits=7)),
                ('price_per_liter', models.DecimalField(decimal_places=2, max_digits=7)),
                ('purchased_at', models.DateTimeField()),
                ('fuel_card_number', models.CharField(blank=True, max_length=30)),
                ('receipt_photo', models.FileField(blank=True, upload_to='fuel_receipts/%Y/%m/')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_transactions', to='logistics.route')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('fuel', 'ГСМ'), ('maintenance', 'Ремонт и ТО'), ('salary', 'Заработная плата'), ('warehouse', 'Складские расходы'), ('other', 'Прочее')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('incurred_at', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, upload_to='expenses/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='logistics.route')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='vehicles.vehicle')),
            ],
        ),
    ]
