# Generated by Django 4.2.24 on 2025-09-27 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField()),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume_m3', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('shipper', models.CharField(max_length=255)),
                ('consignee', models.CharField(max_length=255)),
                ('vat_status', models.CharField(choices=[('with_vat', 'С НДС'), ('without_vat', 'Без НДС')], default='with_vat', max_length=15)),
                ('is_return_trip', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrived_at', models.DateTimeField()),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_entries', to='warehouse.cargo')),
            ],
        ),
    ]
