# Generated by Django 4.2.24 on 2025-09-29 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField()),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume_m3', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('customer', models.CharField(max_length=255)),
                ('consignee', models.CharField(max_length=255)),
                ('vat_status', models.CharField(choices=[('with_vat', 'С НДС'), ('without_vat', 'Без НДС')], default='with_vat', max_length=15)),
                ('is_return_trip', models.BooleanField(default=False)),
                ('invoice_number', models.CharField(blank=True, max_length=50)),
                ('act_number', models.CharField(blank=True, max_length=50)),
                ('invoice_act_number', models.CharField(blank=True, max_length=50)),
                ('document_driver', models.CharField(blank=True, max_length=255)),
                ('route_from', models.CharField(max_length=255)),
                ('route_to', models.CharField(max_length=255)),
                ('driver', models.ForeignKey(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrived_at', models.DateTimeField()),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_entries', to='warehouse.order')),
            ],
        ),
    ]
