# Generated by Django 4.2.24 on 2025-09-29 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='warehouseentry',
            options={'verbose_name': 'Складская запись', 'verbose_name_plural': 'Складские записи'},
        ),
        migrations.AlterField(
            model_name='order',
            name='act_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер акта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='Код заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='consignee',
            field=models.CharField(max_length=255, verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.CharField(max_length=255, verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='order',
            name='document_driver',
            field=models.CharField(blank=True, max_length=255, verbose_name='Водитель по документам'),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_act_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер счет-фактуры'),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер счета'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_return_trip',
            field=models.BooleanField(default=False, verbose_name='Обратный рейс'),
        ),
        migrations.AlterField(
            model_name='order',
            name='route_from',
            field=models.CharField(max_length=255, verbose_name='Маршрут От'),
        ),
        migrations.AlterField(
            model_name='order',
            name='route_to',
            field=models.CharField(max_length=255, verbose_name='Маршрут До'),
        ),
        migrations.AlterField(
            model_name='order',
            name='vat_status',
            field=models.CharField(choices=[('with_vat', 'С НДС'), ('without_vat', 'Без НДС')], default='with_vat', max_length=15, verbose_name='Статус НДС'),
        ),
        migrations.AlterField(
            model_name='order',
            name='volume_m3',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Объем (м³)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вес (кг)'),
        ),
        migrations.AlterField(
            model_name='warehouseentry',
            name='arrived_at',
            field=models.DateTimeField(verbose_name='Дата прибытия'),
        ),
        migrations.AlterField(
            model_name='warehouseentry',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_entries', to='warehouse.order', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='warehouseentry',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='warehouseentry',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Заметки'),
        ),
        migrations.AlterField(
            model_name='warehouseentry',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата выдачи'),
        ),
    ]
