# Generated by Django 4.2.24 on 2025-09-30 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0002_alter_order_options_alter_warehouseentry_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='consignee',
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Номер заявки'),
        ),
        migrations.AddField(
            model_name='order',
            name='places',
            field=models.PositiveIntegerField(default=1, verbose_name='Места (шт)'),
        ),
        migrations.AddField(
            model_name='order',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ставка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='Складской номер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='document_driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documented_orders', to=settings.AUTH_USER_MODEL, verbose_name='Водитель по документам'),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL, verbose_name='Водитель'),
        ),
    ]
