# Generated by Django 4.2.24 on 2025-10-01 17:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_remove_order_consignee_order_order_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_act',
            field=models.DateField(blank=True, null=True, verbose_name='Дата акта'),
        ),
        migrations.AddField(
            model_name='order',
            name='date_invoice',
            field=models.DateField(blank=True, null=True, verbose_name='Дата счёта'),
        ),
        migrations.AddField(
            model_name='order',
            name='date_invoice_act',
            field=models.DateField(blank=True, null=True, verbose_name='Дата счет-фактуры'),
        ),
        migrations.AddField(
            model_name='order',
            name='date_order',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата заявки'),
        ),
        migrations.AddField(
            model_name='order',
            name='rpo_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер РПО'),
        ),
        migrations.AddField(
            model_name='order',
            name='rpo_status',
            field=models.CharField(choices=[('created', 'Создано'), ('sent', 'Отправлено'), ('delivered', 'Доставлено'), ('problem', 'Проблема')], default='created', max_length=20, verbose_name='Статус РПО'),
        ),
    ]
