# Generated by Django 4.2.24 on 2025-10-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_order_date_act_order_date_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='rpo_status',
            field=models.CharField(choices=[('not_sent', 'Не отправлено'), ('created', 'Создано'), ('sent', 'Отправлено'), ('delivered', 'Доставлено'), ('problem', 'Проблема')], default='not_sent', max_length=20, verbose_name='Статус РПО'),
        ),
    ]
