# Generated by Django 4.2.24 on 2025-10-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_alter_order_rpo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='document_driver',
            field=models.CharField(blank=True, default=(('accounts', '0001_initial'),), max_length=255, verbose_name='Водитель по документам'),
            preserve_default=False,
        ),
    ]
