# Generated by Django 4.2.24 on 2025-10-02 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
        ('warehouse', '0006_alter_order_document_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='actual_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='vehicles.vehicle', verbose_name='Машина по факту'),
        ),
        migrations.AddField(
            model_name='order',
            name='document_vehicle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Машина по документам'),
        ),
    ]
