# Generated by Django 4.2.24 on 2025-10-05 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_order_delivery_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rpo_number', models.CharField(blank=True, max_length=50, verbose_name='Номер РПО')),
                ('service', models.CharField(choices=[('pochta', 'Почта России'), ('sdek', 'СДЭК'), ('unknown', 'Неопределено')], default='unknown', max_length=20, verbose_name='Служба')),
                ('shipping_date', models.DateField(blank=True, null=True, verbose_name='Дата отправки')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Дата доставки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postal_records', to='warehouse.order', verbose_name='Заявка')),
            ],
        ),
    ]
