# Generated by Django 4.2.24 on 2025-10-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_postalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отправки'),
        ),
    ]
