# Generated by Django 4.2.24 on 2025-10-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='fired_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата увольнения'),
        ),
        migrations.AddField(
            model_name='user',
            name='inn',
            field=models.CharField(blank=True, max_length=20, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_issued_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи паспорта'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_issued_by',
            field=models.CharField(blank=True, max_length=255, verbose_name='Кем выдан паспорт'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Паспорт (серия и номер)'),
        ),
        migrations.AddField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, max_length=150, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_main',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон основной'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_work',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон рабочий'),
        ),
        migrations.AddField(
            model_name='user',
            name='snils',
            field=models.CharField(blank=True, max_length=20, verbose_name='СНИЛС'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hired_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата трудоустройства'),
        ),
    ]
