# Generated by Django 4.2.24 on 2025-10-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_birth_date_user_fired_at_user_inn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_main',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон основной'),
        ),
    ]
