# Generated by Django 4.2.24 on 2025-09-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('vin', models.CharField(blank=True, max_length=17)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'В эксплуатации'), ('maintenance', 'На обслуживании'), ('inactive', 'Неактивен')], default='active', max_length=20)),
                ('mileage', models.PositiveIntegerField(default=0)),
                ('fuel_type', models.CharField(default='diesel', max_length=20)),
                ('is_collector', models.BooleanField(default=False)),
                ('last_service_at', models.DateField(blank=True, null=True)),
                ('payload_capacity_kg', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['plate_number'],
            },
        ),
    ]
