# Generated by Django 4.2.24 on 2025-10-03 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='hitched_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_collector': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trailers', to='vehicles.vehicle', verbose_name='Привязан к автомобилю'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='is_collector',
            field=models.BooleanField(default=False, verbose_name='Полуприцеп/Прицеп'),
        ),
    ]
