# Generated by Django 4.2.24 on 2025-10-04 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_hitched_to_alter_vehicle_is_collector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='fuel_type',
        ),
    ]
