# Generated by Django 4.2.24 on 2025-10-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_remove_vehicle_fuel_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['plate_number'], 'verbose_name': 'Транспортное средство', 'verbose_name_plural': 'Транспортные средства'},
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(max_length=50, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='last_service_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последнего ТО'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='mileage',
            field=models.PositiveIntegerField(default=0, verbose_name='Пробег (км)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(blank=True, max_length=50, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='payload_capacity_kg',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Грузоподъёмность (кг)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Гос. номер'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('active', 'В эксплуатации'), ('maintenance', 'На обслуживании'), ('inactive', 'Неактивен')], default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(blank=True, max_length=17, verbose_name='VIN-код'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Год выпуска'),
        ),
    ]
